export const EXTENSION_DISPLAY_NAME = 'Hanabi Download Manager X';
export const EXTENSION_MANIFEST_NAME = `${EXTENSION_DISPLAY_NAME} Browser Extension`;
export const EXTENSION_DESCRIPTION = `${EXTENSION_DISPLAY_NAME} - Easy Beautiful Fast`;
export const EXTENSION_NOTIFICATION_TITLE = EXTENSION_DISPLAY_NAME;
export const HANABI_DESKTOP_SERVICE_HOST = '127.0.0.1:9710';
export const HANABI_DESKTOP_SERVICE_URL = `http://${HANABI_DESKTOP_SERVICE_HOST}`;
export const FIREFOX_MIN_VERSION = '142.0';
