<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HanabiNeoNSF</AssemblyName>
    <RootNamespace>Hanabi.NeoNSF</RootNamespace>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>false</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <Product>Hanabi NeoNSFX Download Engine</Product>
    <Company>ZZBuAoYe</Company>
  </PropertyGroup>
</Project>
